config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :chats do
    resources :messages, only: [:create]  
  end

  resources :messages, only: [:index, :show, :new, :create, :edit, :update]


  root to: 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all

    can :create, Message
    can [:update, :destroy], Message, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
    belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'
    has_many :messages, dependent: :destroy
    
    validates :sender_id, presence: true
    validates :receiver_id, presence: true
    validate :sender_and_receiver_must_be_different
    
    private
    
    def sender_and_receiver_must_be_different
      if sender_id == receiver_id
        errors.add(:receiver_id, "can't be the same as sender")
      end
    end
  end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
  
  validates :chat_id, presence: true
  validates :user_id, presence: true
  validates :body, presence: true
  
  validate :user_must_be_in_chat
  
  private
  
  def user_must_be_in_chat
    if chat && user && chat.sender_id != user.id && chat.receiver_id != user.id
      errors.add(:user_id, "must be either the sender or receiver of the chat")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :sent_chats, class_name: 'Chat', foreign_key: 'sender_id'
  has_many :received_chats, class_name: 'Chat', foreign_key: 'receiver_id'
  has_many :received_messages, through: :received_chats, source: :messages
  
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

"""
User
email (string)
first_name (string)
last_name (string)

Chat
sender_id (integer)
receiver_id (integer)

Message
chat_id (integer)
user_id (integer)
body (text)
"""

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chats = Chat.all
  end

  def show
    @chat = Chat.find(params[:id])
    @message = Message.new(chat_id: @chat.id)
  end

  def new
    @chat = Chat.new
    @users = User.all
  end

  def create
    @chat = Chat.new(chat_params)

    if @chat.save
      redirect_to @chat, notice: 'Chat was successfully created.'
    else
      @users = User.all
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @chat = Chat.find(params[:id])
    @users = User.all
  end

  def update
    @chat = Chat.find(params[:id])
    if @chat.update(chat_params)
      redirect_to @chat, notice: 'Chat was successfully updated.'
    else
      @users = User.all
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:sender_id, :receiver_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @messages = @messages.includes(:user, :chat).order(created_at: :desc)
  end

  def show
    # @message 
  end

  def new
    @chats = Chat.all
    @users = User.all
  end

  def create
    if params[:chat_id]
      @chat = Chat.find(params[:chat_id])
      @message.chat = @chat
    end

    if @message.save
      redirect_to chat_path(@message.chat), notice: 'Message was successfully sent.'
    else
      if params[:chat_id]
        render 'chats/show', status: :unprocessable_entity
      else
        @chats = Chat.all
        @users = User.all
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    @chats = Chat.all
    @users = User.all
  end

  def update
    if @message.update(message_params)
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      @chats = Chat.all
      @users = User.all
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id, :chat_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: chat, local: true) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>
      <ul>
        <% chat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sender_id, "Sender" %>
    <%= form.collection_select :sender_id, @users, :id, :email, { include_blank: "Select a sender" } %>
  </div>

  <div class="field">
    <%= form.label :receiver_id, "Receiver" %>
    <%= form.collection_select :receiver_id, @users, :id, :email, { include_blank: "Select a receiver" } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Edit Chat</h1>
<%= render 'form', chat: @chat %>
<div class="links">
  <%= link_to 'Back to Chat', chat_path(@chat) %>
</div>

app/views/chats/index.html.erb
<h1>Chats</h1>

<% if @chats.any? %>
  <table>
    <thead>
      <tr>
        <th>Sender</th>
        <th>Receiver</th>
        <th>Messages</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @chats.each do |chat| %>
        <tr>
          <td><%= chat.sender.email %></td>
          <td><%= chat.receiver.email %></td>
          <td><%= chat.messages.count %></td>
          <td>
            <%= link_to 'View Chat', chat %> |
            <%= link_to 'Edit', edit_chat_path(chat) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No chats found.</p>
<% end %>

<div class="links">
  <%= link_to 'Start New Chat', new_chat_path %>
  <%= link_to 'Back to Users', users_path %>
  <%= link_to 'Create New Message', new_message_path %>
</div>

app/views/chats/new.html.erb
<h1>New Chat</h1>
<%= render 'form', chat: @chat %>
<div class="links">
  <%= link_to 'Back to Chats', chats_path %>
</div>

app/views/chats/show.html.erb
<h1>Chat</h1>
<p><%= link_to 'Edit Chat', edit_chat_path(@chat) %></p>

<p>
  <strong>Sender:</strong>
  <%= @chat.sender.email %> (<%= @chat.sender.first_name %> <%= @chat.sender.last_name %>)
</p>

<p>
  <strong>Receiver:</strong>
  <%= @chat.receiver.email %> (<%= @chat.receiver.first_name %> <%= @chat.receiver.last_name %>)
</p>

<h2>Messages</h2>

<% if @chat.messages.any? %>
  <div class="messages">
    <% @chat.messages.order(created_at: :asc).each do |message| %>
      <div class="message">
        <p>
          <strong><%= message.user.first_name %>:</strong>
          <%= message.body %>
          <small><%= message.created_at.strftime("%b %d, %Y %H:%M") %></small>
        </p>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No messages yet.</p>
<% end %>

<h3>Send a Message</h3>

<%= form_with(model: [@chat, @message], local: true) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :chat_id, value: @chat.id %>
  
  <div class="field">
    <%= form.label :user_id, "From" %>
    <%= form.collection_select :user_id, [@chat.sender, @chat.receiver], :id, :email %>
  </div>

  <div class="field">
    <%= form.label :body, "Message" %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit "Send Message" %>
  </div>
<% end %>

<div class="links">
  <%= link_to 'Back to Chats', chats_path %>
  <%= link_to 'All Users', users_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Whats New" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">WhatsNew</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Chats', chats_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Messages', messages_path, class: 'nav-link' %></li>
          </ul>

          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
              <li class="nav-item">
                <span class="navbar-text text-light me-2">Welcome, <%= current_user.email %></span>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :chat_id, "Chat" %>
    <%= form.collection_select :chat_id, @chats, :id, :id, { include_blank: "Select a chat" } %>
  </div>

  <div class="field">
    <%= form.label :user_id, "From (User)" %>
    <%= form.collection_select :user_id, @users, :id, :email, { include_blank: "Select a user" } %>
  </div>

  <div class="field">
    <%= form.label :body, "Message" %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form', message: @message %>
<div class="links">
  <%= link_to 'Back to Message', message_path(@message) %>
</div>

app/views/messages/index.html.erb
<h1>Messages</h1>

<% if @messages.any? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Chat</th>
        <th>Sender</th>
        <th>Body</th>
        <th>Timestamp</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= message.id %></td>
          <td>
            Chat <%= message.chat.id %><br>
            (<%= message.chat.sender.email %> → <%= message.chat.receiver.email %>)
          </td>
          <td><%= message.user.email %></td>
          <td><%= truncate(message.body, length: 40) %></td>
          <td><%= message.created_at.strftime("%b %d, %Y %H:%M") %></td>
          <td>
            <%= link_to 'View Message', message_path(message) %>
            <% if can? :edit, message %>
              | <%= link_to 'Edit', edit_message_path(message) %>
            <% end %>
            <% if can? :destroy, message %>
              | <%= link_to 'Delete', message_path(message), method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No messages found.</p>
<% end %>

<div class="links">
  <% if can? :create, Message %>
    <%= link_to 'Create New Message', new_message_path %>
  <% end %>
  <%= link_to 'Back to Chats', chats_path %>
  <%= link_to 'All Users', users_path %>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'form', message: @message %>
<div class="links">
  <%= link_to 'Back to Messages', messages_path %>
  <%= link_to 'Back to Users', users_path %>
</div>

app/views/messages/show.html.erb
<h1>Message ID <%= @message.id %></h1>

<p>
  <strong>Chat:</strong>
  <%= link_to "Chat ##{@message.chat.id}", chat_path(@message.chat) %><br>
  (<%= @message.chat.sender.email %> → <%= @message.chat.receiver.email %>)
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.user.email %> (<%= @message.user.first_name %> <%= @message.user.last_name %>)
</p>

<p>
  <strong>Content:</strong><br>
  <%= simple_format(@message.body) %>
</p>

<p>
  <strong>Sent At:</strong>
  <%= @message.created_at.strftime("%b %d, %Y %H:%M") %>
</p>

<div class="links">
  <%= link_to 'Back to Messages', messages_path %>
</div>

<% if can? :edit, @message %>
  <p><%= link_to 'Edit Message', edit_message_path(@message) %></p>
<% end %>

<% if can? :destroy, @message %>
  <p><%= link_to 'Delete Message', message_path(@message), method: :delete, data: { confirm: "Are you sure?" } %></p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">WhatsNew</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Chats', chats_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Messages', messages_path, class: 'nav-link' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form', user: @user %>
<div class="links">
  <%= link_to 'Back to User', user_path(@user) %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<% if @users.any? %>
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Messages Sent</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.messages.count %></td> <!-- NUEVO -->
          <td>
            <%= link_to 'Show', user %> |
            <%= link_to 'Edit', edit_user_path(user) %> <!-- NUEVO -->
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
<% else %>
  <p>No users found.</p>
<% end %>

<div class="links">
  <%= link_to 'Add New User', new_user_path %>
  <%= link_to 'View Chats', chats_path %>
  <%= link_to 'Create New Message', new_message_path %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form', user: @user %>
<div class="links">
  <%= link_to 'Back to Users', users_path %>
</div>

app/views/users/show.html.erb
<h1>User Details</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<h2>Sent Chats</h2>
<% if @user.sent_chats.any? %>
  <ul>
    <% @user.sent_chats.each do |chat| %>
      <li><%= link_to "Chat with #{chat.receiver.email}", chat_path(chat) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No sent chats.</p>
<% end %>

<h2>Received Chats</h2>
<% if @user.received_chats.any? %>
  <ul>
    <% @user.received_chats.each do |chat| %>
      <li><%= link_to "Chat with #{chat.sender.email}", chat_path(chat) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No received chats.</p>
<% end %>

<h2>Messages Sent</h2>
<% if @user.messages.any? %>
  <ul>
    <% @user.messages.each do |msg| %>
      <li>
        To <%= msg.chat.receiver.email %>:
        "<%= truncate(msg.body, length: 50) %>"
        (<%= link_to 'View', message_path(msg) %>)
      </li>
    <% end %>
  </ul>
<% else %>
  <p>This user hasn't sent any messages.</p>
<% end %>

<%= link_to 'Edit User', edit_user_path(@user) %>

<div class="links">
  <%= link_to 'Back to Users', users_path %>
  <%= link_to 'Start a New Chat', new_chat_path %>
</div>